### ISSUE TITLE
1.19.4进入单人存档游戏崩溃

### ISSUE THREAD

**Issue by snpdzk** [Gu-ZT/gugle-carpet-addition#19]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-04-27 01:19:09
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: carpet/fakes/ServerPlayerEntityInterface
	at dev.dubhe.gugle.carpet.tools.FakePlayerInventoryContainer.<init>(FakePlayerInventoryContainer.java:42)
	at dev.dubhe.gugle.carpet.GcaExtension.onPlayerLoggedIn(GcaExtension.java:53)
	at carpet.CarpetServer.lambda$onPlayerLoggedIn$8(CarpetServer.java:181)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at carpet.CarpetServer.onPlayerLoggedIn(CarpetServer.java:181)
	at net.minecraft.class_3324.handler$zmo000$carpet$onPlayerConnected(class_3324.java:2497)
	at net.minecraft.class_3324.method_14570(class_3324.java:301)
	at net.minecraft.class_3248.method_33800(class_3248.java:131)
	at net.minecraft.class_3248.method_14384(class_3248.java:118)
	at net.minecraft.class_3248.redirect$ddb000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18784(class_3248.java:68)
	at net.minecraft.class_2535.method_10754(class_2535.java:254)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$zlj000$carpet$modifiedRunLoop(MinecraftServer.java:2936)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: carpet.fakes.ServerPlayerEntityInterface
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 362181776 bytes (345 MiB) / 1128267776 bytes (1076 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 59719.05
	Virtual memory used (MB): 41413.59
	Swap memory total (MB): 27114.55
	Swap memory used (MB): 5884.41
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.4-fabric0.76.0-1.3.1
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.73
		autofish: Autofish 0.9.8-SNAPSHOT
		badpackets: Bad Packets 0.4.1
		beenfo: Beenfo 1.19.3-fabric0.68.1-1.3.3
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		betterpingdisplay: Better Ping Display 1.1.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.28
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.28
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.28
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.28
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.28
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.28
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.28
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.28
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.28
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.28
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.28
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.28
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.28
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.28
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.28
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.28
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.28
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.28
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.28
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.10.28
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.28
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		capes: Capes 1.5.2+1.19.3
		carpet: Carpet Mod 1.4.100+v230314
		carpet-extra: Carpet Extra 1.4.100
		carpet-tis-addition: Carpet TIS Addition 1.46.1
			conditional-mixin: conditional mixin 0.3.2
		chat_heads: Chat Heads 0.10.12
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 11.0.0.2
		debugify: Debugify 1.19.4+2.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		exordium: Exordium 1.0.3-mc1.19.4
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		fabricskyboxes: FabricSkyBoxes 0.6.5+mc1.19.4
		fastchest: FastChest 1.4+1.19.3
		ferritecore: FerriteCore 5.2.0
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		g4mespeed: G4mespeed 1.3.4
		gca: GugleCarpetAddition 2.6.0-1.19
		ias: In-Game Account Switcher 8.0.1.2
		imblocker: IMBlockerFabric 1.0.20_pre5
		indium: Indium 1.0.15+mc1.19.4
		inventoryprofilesnext: Inventory Profiles Next 1.9.3
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller craftfix-1.2.7
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libipn: libIPN 2.0.3
		litematica: Litematica 0.14.3
		lithium: Lithium 0.11.1
		magiclib: MagicLib 0.7.317+92abd79-beta
			magiclib-1_19_4: MagicLib for 1.19.4 0.7.317+92abd79-beta
		malilib: MaLiLib 0.15.2
		masa_gadget_mod: Masa Gadget 3.1.289+1ca4352-stable
			masa_gadget_mod-1_19_4: Masa Gadget for 1.19.4 3.1.289+1ca4352-stable
		memoryleakfix: Memory Leak Fix 1.0.0
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		modmenu: Mod Menu 6.1.0-rc.4
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		ommc: Oh My Minecraft Client 0.5-beta+ec9da71
			ommc-1_19_4: Oh My Minecraft Client for 1.19.4 0.5-beta+ec9da71
		pca: Plusls Carpet Addition 0.3.154+75f455c-beta
			pca-1_19_4: Plusls Carpet Addition 0.3.154+75f455c-beta
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.8.0
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		syncmatica: Syncmatica 1.18.2-0.3.8
		tweakermore: TweakerMore 3.11.0
		tweakeroo: Tweakeroo 0.16.0
		viafabric: ViaFabric 0.4.10+33-dev
			org_yaml_snakeyaml: snakeyaml 2.0
			viafabric-mc119: ViaFabric for 1.19 0.4.10+33-dev
			viaversion: ViaVersion 4.7.0-23w14a-SNAPSHOT
		wthit: wthit 7.2.2
		xaero_map_addition: Xaero Map Addition 0.2.3
		xaerominimap: Xaero's Minimap 23.3.1
		xaeroworldmap: Xaero's World Map 1.29.2
		yet-another-config-lib: YetAnotherConfigLib 2.4.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['snp_bot'/161, l='ServerLevel[新的世界]', x=-119.50, y=64.00, z=35.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.4-test

**Comment by zHElEARN** [comment]
同样有此问题，怎么修复的

**Comment by zHElEARN** [comment]
> 同样有此问题，怎么修复的

已解决 用1.19.4的即可
