### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Pau1am** [Gu-ZT/gugle-carpet-addition#2]
1.假人无敌：开启后假人不会受到任何伤害，并且饥饿值不会减少。
                     这可用于假人在空旷环境长时间挂机时，不会被幻翼等生物击杀

2.假人禁止拾取物品：开启后假人不会吸取附近的掉落物
                                    这可避免假人在使用大量掉落物的机器时，拾取过多物品导致背包被占满

3.玩家自动补货：将假人自动补货的机制移植至玩家，因为我看目前其他的地毯附属貌似没有这个功能

4.村民背包管理：可以通过右键村民打开其背包，并且进行调整，类似于假人的背包管理

**Comment by Gu-ZT** [comment]
1.可以通过将假人包裹起来避免
2.你可以先自行把假人背包占满
3.玩家的都有其它客户端模组帮助了，不是很需要
4.村民的背包只背种子和食物，没什么必要去管理

**Comment by Pau1am** [comment]
对于第四点建议，我给予一下补充说明为何加入这个功能。

之前我在制作村民繁殖机的时候不小心给村民丢太多食物，导致他们背包空间占满，而无法交换食物进行繁殖，进而造成一些小麻烦。因此我认为加入该功能的主要原因是避免这样的问题。

此外，加入该功能也可让玩家确认村民背包内的食物数量，从而做到精准繁殖的效果，确保繁殖出限定数量的小村民。

另外，如果条件允许，我也建议做出对其他生物的背包管理，如僵尸村民，这对部分机器的制作也有一定的容错率，比如制作僵尸村民伪和平时，僵尸村民若不小心拾取玩家物品则不会计入刷怪上限，加入背包管理功能能够有效解决这个问题。

虽然这些问题都能够通过其他原版的方式解决，但在部分条件下也十分麻烦，例如某个玩家不小心死在伪和平机器里，导致大量僵尸获得玩家物品，从而需要处理大量僵尸。

至于前面三点建议确实有其他mod或利用原版功能进行替代，只是第四个功能我认为比较重要，且目前据我所知没有任何mod据有类似功能。因此希望作者大大能考虑一下这个功能。

（如果对多生物的背包编辑较难制作，或许可以做一个功能让生物丢出其背包内的物品或者手持物品,希望上述建议能得到采纳,十分感谢。）

**Comment by Gu-ZT** [comment]
Give up
