### ISSUE TITLE
Outdated translation keys

### ISSUE THREAD

**Issue by vocaloidkiss** [Gu-ZT/gugle-carpet-addition#22]
![图片](https://github.com/Gu-ZT/gugle-carpet-addition/assets/115659586/27fc08ab-bc76-495e-8dfc-3ebc6ad05d2c)
翻译组件字符问题

**Comment by Gu-ZT** [comment]
#20

**Comment by vocaloidkiss** [comment]
我该怎么做，这会导致假人驻留功能开启后，服务器重启时，假人加载世界并crash
