### ISSUE TITLE
2.6.0 版本会导致原版合成书快速合成行为异常

### ISSUE THREAD

**Issue by LittleCircleOO** [Gu-ZT/gugle-carpet-addition#23]
### 问题描述
在加入 GugleCarpetAddition 后，会导致原版合成书快速合成功能异常。
### 版本
Minecraft 1.20
Fabric Loader 0.14.21
Fabric Api 0.83.0
Carpet 1.4.112 v230608
gugle-carpet-addition 2.6.0
### 复现步骤
上述模组中，去除 gugle-carpet-addition，放置工作台，拿取一组铁锭，Shift+左键点击配方书中的铁块，如图所示，物品正常转移。
![feedback_normal](https://github.com/Gu-ZT/gugle-carpet-addition/assets/51949761/649ae425-a76d-4de7-b9ed-30743f61afe2)
当加入 gugle-carpet-addition 后，以同样的方式操作，物品转移行为异常，在此期间未调整任何地毯规则。
![feedback_issue](https://github.com/Gu-ZT/gugle-carpet-addition/assets/51949761/874a69e7-d0f7-461e-8cde-2896eaf24cdb)

**Comment by Gu-ZT** [comment]
这倒不是BUG，算是我本地测试的实验性功能，发布的时候忘删了，其实是为了喷射合成的时候在背包里保留一个物品，免得没有足够的空间拾取新的物品

**Comment by LittleCircleOO** [comment]
> 这倒不是BUG，算是我本地测试的实验性功能，发布的时候忘删了，其实是为了喷射合成的时候在背包里保留一个物品，免得没有足够的空间拾取新的物品

但这一设计违背了地毯及其附属mod“默认配置下不对游戏机制进行改动”的原则，可否提供规则开关供用户自行调整？

**Comment by Adogs1** [comment]
> 这倒不是BUG，算是我本地测试的实验性功能，发布的时候忘删了，其实是为了喷射合成的时候在背包里保留一个物品，免得没有足够的空间拾取新的物品

所以它在以后版本还有这个功能吗？不太想用李芒果的复杂合成
