### ISSUE TITLE
set fakePlayerResident to true but didn't work

### ISSUE THREAD

**Issue by IntangibleW** [Gu-ZT/gugle-carpet-addition#30]
Fake players disappear when server restart, even `fakePlayerResident` set to `true`.
Besides, I checked logs that shows
"User \<uuid\> - \<fakeplayername\> doesn't currently have data pre-loaded - denying login."
when a fake player is being spawned. Don't know whether this is related to this issue.

Game version: 1.20.1
Mod version: 2.7.0

**Comment by YOtsuha106** [comment]
the same pb

**Comment by swe3per** [comment]
the same pb

**Comment by swe3per** [comment]
经过测试 是2.7.0的假人控制模组会出现这个bug，回退到2.6.0就没有这个问题了。

**Comment by YOtsuha106** [comment]
谢谢，已经提前回退了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 晚上6:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gu-ZT/gugle-carpet-addition] set fakePlayerResident to true but didn&#39;t work (Issue #30)





 
经过测试 是2.7.0的假人控制模组会出现这个bug，回退到2.6.0就没有这个问题了。
