### ISSUE TITLE
可以移植到1.12版本吗？

### ISSUE THREAD

**Issue by CoderTCY** [Gu-ZT/gugle-carpet-addition#33]
Forge和文件覆盖都行

**Comment by Gu-ZT** [comment]
我以为1.13已经是天下第一了，没想到有人比它还勇猛，这是谁的部将

**Comment by CoderTCY** [comment]
> 我以为1.13已经是天下第一了，没想到有人比它还勇猛，这是谁的部将

carpet作者的^_^

**Comment by CoderTCY** [comment]
去翻了一下carpet 1.12的源码，发现是有我想要的假人驻留的。
不过这个issue我还是开着吧，毕竟还有假人物品栏呢
