### ISSUE TITLE
如何使用更好的栅栏门放置？

### ISSUE THREAD

**Issue by vocaloidkiss** [Gu-ZT/gugle-carpet-addition#34]
这个规则的描述毫无帮助，我完全不能明白，应该通过什么操作来选中一个栅栏门的状态

**Comment by Gu-ZT** [comment]
例如你对着一个已经放置在世界中的朝向西边且打开的栅栏门放置你手中的栅栏门时，你所新放置的栅栏门会完全拷贝已经处于世界中的那个栅栏门的方块状态，即朝向西边且打开，而无论你的朝向如何

**Comment by vocaloidkiss** [comment]
谢谢你
