### ISSUE TITLE
1.20.1假人补货失效

### ISSUE THREAD

**Issue by hookzeds** [Gu-ZT/gugle-carpet-addition#46]
起初，我正在服务器挂杀凋机，但是发现假人不会自动补货，于是我去单人存档测试，得到了相同的结果，排除服务器的问题，然后我下了一个纯净的fabric端(仅有gca和carpet)，还是一样的结果，我不理解为什么，明明前段时间还好好的

**Comment by shuangshun** [comment]
副手可以,主手好像只是放方块的时候不能补货
