### ISSUE TITLE
召唤假人导致游戏崩溃

### ISSUE THREAD

**Issue by PeterTerpe** [Gu-ZT/gugle-carpet-addition#52]
Fabric 1.20.4 服务端，有时召唤假人会导致游戏崩溃。会出问题的假人都是之前召唤过的。
[2024-05-10-5.log](https://github.com/Gu-ZT/gugle-carpet-addition/files/15274199/2024-05-10-5.log)
[crash-2024-05-10_18.43.15-server.txt](https://github.com/Gu-ZT/gugle-carpet-addition/files/15274200/crash-2024-05-10_18.43.15-server.txt)

**Comment by liangmiQwQ** [comment]
一摸一样，正在寻找解决方案

**Comment by AresConnor** [comment]
因为这个模组，服务器招假人时不时崩服已经半年了，相同报错
