### ISSUE TITLE
Will update 1.21

### ISSUE THREAD

**Issue by KleinQwQ** [Gu-ZT/gugle-carpet-addition#55]
### Matters to be added to TODO - 将要加入TODO的事项

update gca to 1.21

### Describe what this TODO will do - 描述这个TODO要做的事情

please update gca to 1.21

**Comment by Gu-ZT** [comment]
I think, as I have explained in the issue template, this is an internal issue template for a project, please do not use this template! Unless you are an internal member of the project, you should not use this issue template, which is ordering me! And you shouldn't order me to do anything, even if it is in my plan!

**Comment by Adogs1** [comment]
> ### Matters to be added to TODO - 将要加入TODO的事项
> 将 GCA 更新到 1.21
> 
> ### Describe what this TODO will do - 描述这个TODO要做的事情
> 请将 GCA 更新到 1.21

你可以在行动中获取build构建
