### ISSUE TITLE
[Bug] fakePlayerResident doesn't work / fakePlayerResident 功能非正常工作

### ISSUE THREAD

**Issue by huanqiugame** [Gu-ZT/gugle-carpet-addition#62]
### OS Version - 操作系统

macOS

### Minecraft Version Details - Minecraft 版本信息

1.21

### Version Details - 版本信息

GCA 2.9.0+build.51 / Carpet 1.4.147+v240613

### Existing behavior - 现有行为

When you join a world that contains fake player before quitting, the fake player disappears. After checking `fake_player.gca.json`, it was found that regardless of whether there was a fake player before exiting the world, `fake_player.gca.json` was always written as `{}`.
当你加入一个退出前包含假人的世界时，假人消失。检查`fake_player.gca.json`后发现无论退出世界前是否有假人，`fake_player.gca.json`始终写入为`{}`。

### Expected behavior - 预期行为

When you join a world with fake player existed when you quit the world, the fake player stays where it was, and `fake_player.gca.json` is written normally. Additionally, if the fakePlayerReloadAction rule is set to true, the fake player should do what it was doing.
当你加入一个退出前包含假人的世界时，假人仍在其原来的位置，且`fake_player.gca.json`正常写入。此外，如果fakePlayerReloadAction规则设置为true，则假人应仍在执行退出前应做的事。

### To Reproduce - 复现问题

1. Join a world with command enabled in Minecraft 1.21 with all necessary mods installed correctly. 在Minecraft 1.21中加入允许命令的世界，并正确安装所有必要的模组。
2. Run the following commands: 运行以下命令：
2.1. `/carpet fakePlayerResident true`
2.2. `/carpet setDefault fakePlayerResident true`
2.3. `/player Test spawn`
3. Press `ESC` and click “Save and Quit to Title”. 按下`ESC`，并点按“保存并退回到标题画面”。
4. Go to your `saves/<WORLD NAME>` folder, and notice `fake_player.gca.json` is `{}`. 转到`saves/<WORLD NAME>`文件夹，注意到`fake_player.gca.json`为`{}`。
5. Join the world mentioned above. The fake player is gone. 加入上述世界。假人消失。

### This issue is unique - 这个issue是唯一的

- [x] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

*This is the first issue with Minecraft 1.21. Other versions have had similar problems many times, but all issues have been closed. 在1.21版本下此为首次。其他版本已多次出现类似问题但所有issue都为已关闭。*

**Comment by ghost** [comment]
build.50正常，疑似是 @zly2006 的PR导致 #61

**Comment by huanqiugame** [comment]
感谢！我稍后有时间就编译测试一下。

**Comment by zly2006** [comment]
> 感谢！我稍后有时间就编译测试一下。

已经修了：https://github.com/Gu-ZT/gugle-carpet-addition/pull/63
