### ISSUE TITLE
[Feature] Request for Minecraft 1.20.6

### ISSUE THREAD

**Issue by ZeroCore-Zero** [Gu-ZT/gugle-carpet-addition#64]
### What new features do you want? - 你想要什么新功能？

Requests for a new release of GCA for Minecraft 1.20.6

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by YorigamiChitose** [comment]
same

**Comment by iCuraCN** [comment]
+1 PLZZZZZZZZZZ!!!

**Comment by Poroxx0311** [comment]
+1

**Comment by CaDofin0514** [comment]
+1
