### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Hoicey522** [Gu-ZT/gugle-carpet-addition#83]
### OS Version - 操作系统

Windows

### Minecraft Version Details - Minecraft 版本信息

1.21.1

### Version Details - 版本信息

1.21.1 build82

### Existing behavior - 现有行为

在存档有假人 时候（开启假人驻留），此build比较大可能导致在进入存档的时候卡在加载100%，附件是所使用的mod，退回build80版本无此问题
![image](https://github.com/user-attachments/assets/76086313-2b4b-468b-b635-fbab56199b3b)

### Expected behavior - 预期行为

修复此bug

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Hoicey522** [comment]
建议其他人留意有无此情况发生

**Comment by fcsailboat** [comment]
提供一下游戏日志

**Comment by Hoicey522** [comment]
这俩的其中一个或者两个都是（没记错的话）
[2024-11-10-4.log](https://github.com/user-attachments/files/17691698/2024-11-10-4.log)
[2024-11-10-5.log](https://github.com/user-attachments/files/17691702/2024-11-10-5.log)

**Comment by Hoicey522** [comment]
加载进度卡在100%我用启动器强制结束游戏

**Comment by fcsailboat** [comment]
存档根目录下有没有一个fake_player.gca.json文件

**Comment by fcsailboat** [comment]
无法复现

**Comment by Hoicey522** [comment]
> 存档根目录下有没有一个fake_player.gca.json文件

存在此文件，需要如何处理？存档现在没有放假人，文件里面只有俩括号
![image](https://github.com/user-attachments/assets/23ff738d-5a1a-4a08-9ca7-e6e570563f9b)

**Comment by fcsailboat** [comment]
看起来没有假人被加载，你确定是假人驻留的问题吗

**Comment by fcsailboat** [comment]
试试用记事本打开存档根目录下的`carpet.conf`，删除`fakePlayerResident true`和`fakePlayerReloadAction true`后能不能正常启动游戏

**Comment by Hoicey522** [comment]
> 试试用记事本打开存档根目录下的`carpet.conf`，删除`fakePlayerResident true`和`fakePlayerReloadAction true`后能不能正常启动游戏

在存档设置了假人和动作后，按照你的操作之后可以正常进入存档，只不过假人没了而已。### **估计是build82可能和其他mod冲突了吧**，要不此issue先关闭？要不还再发生我再提交反馈
