### ISSUE TITLE
[Bug] 更好的告示牌交互

### ISSUE THREAD

**Issue by beijuren** [Gu-ZT/gugle-carpet-addition#86]
### OS Version - 操作系统

Windows

### Minecraft Version Details - Minecraft 版本信息

1.21.1

### Version Details - 版本信息

gugle-carpet-addition-mc1.21.1-2.9.0+build.84

### Existing behavior - 现有行为

在开启后，右键交互附着在箱子的告示牌，打开的是告示牌修改UI

### Expected behavior - 预期行为

在开启后，右键交互附着在箱子的告示牌，打开的是箱子

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by beijuren** [comment]
同时更好的展示框交互开启后，我似乎不能把展示框取下了？几乎是单方面对我无敌，要用什么特殊方法吗？

**Comment by Gu-ZT** [comment]
更好的告示牌交互在新版本更改为在涂蜡的告示牌上生效，想要拆卸/旋转展示框需要任意手持有仙人掌，在此基础上另一手持有玻璃/玻璃板（未染色）右键展示框可以隐藏展示框

**Comment by beijuren** [comment]
> 更好的告示牌交互在新版本更改为在涂蜡的告示牌上生效，想要拆卸/旋转展示框需要任意手持有仙人掌，在此基础上另一手持有玻璃/玻璃板（未染色）右键展示框可以隐藏展示框

我还是更喜欢直接生效，潜行修改这个效果o(╯□╰)o
